/* Generated by tools/bake_icons.py -- do not edit.
 * Icon font includes and the size -> (text font, icon font) mapping,
 * driven by the SIZES list. Retune fonts via tools/derive_font_sizes.py.
 * Included by main/ui/theme.c after theme_font_pair_t is defined.
 */
#ifndef ICONS_FONTS_H
#define ICONS_FONTS_H

#if !defined(ICONS_16) || ICONS_16
#include "icons_16.h"
#endif
#if !defined(ICONS_22) || ICONS_22
#include "icons_22.h"
#endif
#if !defined(ICONS_24) || ICONS_24
#include "icons_24.h"
#endif
#if !defined(ICONS_28) || ICONS_28
#include "icons_28.h"
#endif
#if !defined(ICONS_30) || ICONS_30
#include "icons_30.h"
#endif
#if !defined(ICONS_32) || ICONS_32
#include "icons_32.h"
#endif
#if !defined(ICONS_34) || ICONS_34
#include "icons_34.h"
#endif
#if !defined(ICONS_40) || ICONS_40
#include "icons_40.h"
#endif

/* Each board enables only the two sizes its policy selects; pruned
 * sizes are compiled out by their ICONS_<size>=0 guard. */
static theme_font_pair_t font_pair_for_size(uint16_t size) {
  switch (size) {
#if LV_FONT_MONTSERRAT_16 && (!defined(ICONS_16) || ICONS_16)
  case 16:
    return (theme_font_pair_t){&lv_font_montserrat_16, &icons_16};
#endif
#if LV_FONT_MONTSERRAT_22 && (!defined(ICONS_22) || ICONS_22)
  case 22:
    return (theme_font_pair_t){&lv_font_montserrat_22, &icons_22};
#endif
#if LV_FONT_MONTSERRAT_24 && (!defined(ICONS_24) || ICONS_24)
  case 24:
    return (theme_font_pair_t){&lv_font_montserrat_24, &icons_24};
#endif
#if LV_FONT_MONTSERRAT_28 && (!defined(ICONS_28) || ICONS_28)
  case 28:
    return (theme_font_pair_t){&lv_font_montserrat_28, &icons_28};
#endif
#if LV_FONT_MONTSERRAT_30 && (!defined(ICONS_30) || ICONS_30)
  case 30:
    return (theme_font_pair_t){&lv_font_montserrat_30, &icons_30};
#endif
#if LV_FONT_MONTSERRAT_32 && (!defined(ICONS_32) || ICONS_32)
  case 32:
    return (theme_font_pair_t){&lv_font_montserrat_32, &icons_32};
#endif
#if LV_FONT_MONTSERRAT_34 && (!defined(ICONS_34) || ICONS_34)
  case 34:
    return (theme_font_pair_t){&lv_font_montserrat_34, &icons_34};
#endif
#if LV_FONT_MONTSERRAT_40 && (!defined(ICONS_40) || ICONS_40)
  case 40:
    return (theme_font_pair_t){&lv_font_montserrat_40, &icons_40};
#endif
  default:
    break;
  }
  /* Fallback so the theme always links; never reached at runtime. */
#if LV_FONT_MONTSERRAT_16 && (!defined(ICONS_16) || ICONS_16)
  return (theme_font_pair_t){&lv_font_montserrat_16, &icons_16};
#elif LV_FONT_MONTSERRAT_22 && (!defined(ICONS_22) || ICONS_22)
  return (theme_font_pair_t){&lv_font_montserrat_22, &icons_22};
#elif LV_FONT_MONTSERRAT_24 && (!defined(ICONS_24) || ICONS_24)
  return (theme_font_pair_t){&lv_font_montserrat_24, &icons_24};
#elif LV_FONT_MONTSERRAT_28 && (!defined(ICONS_28) || ICONS_28)
  return (theme_font_pair_t){&lv_font_montserrat_28, &icons_28};
#elif LV_FONT_MONTSERRAT_30 && (!defined(ICONS_30) || ICONS_30)
  return (theme_font_pair_t){&lv_font_montserrat_30, &icons_30};
#elif LV_FONT_MONTSERRAT_32 && (!defined(ICONS_32) || ICONS_32)
  return (theme_font_pair_t){&lv_font_montserrat_32, &icons_32};
#elif LV_FONT_MONTSERRAT_34 && (!defined(ICONS_34) || ICONS_34)
  return (theme_font_pair_t){&lv_font_montserrat_34, &icons_34};
#elif LV_FONT_MONTSERRAT_40 && (!defined(ICONS_40) || ICONS_40)
  return (theme_font_pair_t){&lv_font_montserrat_40, &icons_40};
#else
#error "theme: no Montserrat icon font size enabled"
#endif
}

#endif // ICONS_FONTS_H
